services:
  spark-master:
    image: bitnami/spark:3.3
    container_name: spark-master  
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./app:/app
      - ./data_input:/data_input
      - ./data_lake:/data_lake
    networks:
      - iot_net
    command: "/opt/bitnami/spark/bin/spark-submit /app/spark_streaming.py"

  spark-worker-1:
    image: bitnami/spark:3.3
    container_name: spark-worker-1  
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - ./data_input:/data_input
      - ./data_lake:/data_lake
    networks:
      - iot_net

  python-ingestor:
    build:
      context: ./app
    container_name: python-ingestor  
    volumes:
      - ./data_input:/data_input
    networks:
      - iot_net

networks:
  iot_net:
    driver: bridge